steps:
  - name: 'ubuntu'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo 'PROJECT_ID: ' ${PROJECT_ID}; \
        echo 'PROJECT_NUMBER: ' ${PROJECT_NUMBER}; \
        echo 'BUILD_ID: ' ${BUILD_ID}; \
        echo '_PROJECT_ID_CHANGED: ' ${_PROJECT_ID_CHANGED}; \
        echo '_PROJECT_NUMBER_CHANGED: ' ${_PROJECT_NUMBER_CHANGED}; \
        echo '_BUILD_ID_CHANGED: ' ${_BUILD_ID_CHANGED}

substitutions:
  _PROJECT_ID_CHANGED: aaaaa${PROJECT_ID}
  _PROJECT_NUMBER_CHANGED: aaaa${PROJECT_NUMBER}
  _BUILD_ID_CHANGED: aaaa${BUILD_ID}

